### ISSUE TITLE
AssertionError in training

### ISSUE THREAD

**Issue by yxlu-0102** [slp-rl/aero#18]
Hello, I ran into this problem when training the aero model:
`assert len(self.hr_set) == len(self.lr_set)
AssertionError`

**Comment by yxlu-0102** [comment]
I should be caused by segmenting, can I set `segment=None`?

**Comment by m-mandel** [comment]
It's been a while since I looked at the code, but if I recall correctly, setting segment=None will cause the dataset to get each sample as a whole. You are welcome to dive into the code here: https://github.com/slp-rl/aero/blob/63fc8a26d96ea0ce39d3a17ef535f4eff186e9ff/src/data/datasets.py#L130.

If you need more assistance, please share the config files you used, and print out the actual length of the hr_set and lr_set you are receiving.

**Comment by yxlu-0102** [comment]
Have you ever trained the model on the condition of 2-16? If you have, can you provide the pre-trained models?
